name: Deploy Node API

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm install
        
      - name: Run tests
        run: npm test
        
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/node-api

            echo "📥 Force sync repo"
            git fetch origin
            git reset --hard origin/main

            echo "🧹 Clean BEFORE build"
            docker system prune -af

            echo "🐳 Rebuild node"
            docker compose build node-api

            echo "🚀 Restart container"
            docker compose up -d node-api

            echo "✅ Node deployed successfully - $(date)"